### ISSUE TITLE
The scan has exceeded the time limit!

### ISSUE THREAD

**Issue by Dj-EKI** [LeandroSQ/android-ble-made-easy#37]
I assume that the error appears when the timeout has been reached. How can I filter this error message so that the app doesn't crash.
Unfortunately it doesn't work with "Try Cache".
It should keep trying to reconnect.

```
GlobalScope.launch {
            // You can specify filters for your device, being them 'macAddress', 'service' and 'name'
            while(true) {
                if (device0 == null || device0!!.isActive == false) {
                    Log.d("BLE_Connection:", "Versuche zu verbinden.")
                    try {
                        val connection = ble.scanFor(
                            // You only need to supply one of these, no need for all of them!
                            name = "EKIsWatch"
                        )
                        // And you can continue with your code
                        READUUID = connection!!.readableCharacteristics[0]
                        WRITEUUID = connection.writableCharacteristics[0]
                        NOTIFYUUID = connection.notifiableCharacteristics[0]
                        connection.write(WRITEUUID, "Testing")
                        device0 = connection
                        Log.d("BLE_Connection:", NOTIFYUUID)
                        delay(1000)
                        DeviceName = "EKIsWatch"
                        connection.observeString(
                            NOTIFYUUID,
                            charset = Charsets.UTF_8
                        ) { value: String ->

                            if (value.startsWith("N/1")) {
                                ReadyToReceive = true
                                Log.d("ReadyToReceive:", ReadyToReceive.toString())
                            }
                            Log.d("BLE_Notify:", value)

                            if (value.startsWith("N/D")) {
                                if (value[3] == 'W'){

                                }
                            }
                        }
                    }
                    catch (e:ScanFailureException){
                        Log.d("BLE_Connection:", e.toString())
                    }
                    finally
                    {

                    }
                    // And it will automatically connect to your device, no need to boilerplate
//                    if (connection != null) {
//
//                        // For watching strings
//                    } else {
//                        // Show an Alert or UI with your preferred error message about the device not being available
//                        Log.d("BLE_Connection:", "Keine Verbindung möglich")
//                        DeviceName = ""
//                        delay(1000)
//                    }
                }else {
                    Log.d("BLE_Connection:", "Keine Verbindung oder Inaktiv.")
                    delay(5000)
                }
            }
        }
```

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: com.example.ekissmartwatch, PID: 15307
    quevedo.soares.leandro.blemadeeasy.exceptions.ScanTimeoutException: The scan has exceeded the time limit!
        at quevedo.soares.leandro.blemadeeasy.BLE$scanFor$2$1.invokeSuspend(BLE.kt:719)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8252)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@410c56e, Dispatchers.Default]
W/DefaultDispatch: type=1400 audit(0.0:59214): avc: denied { search } for name="miuilog" dev="dm-45" ino=448 scontext=u:r:untrusted_app:s0:c59,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.ekissmartwatch
W/DefaultDispatch: type=1400 audit(0.0:59215): avc: denied { search } for name="miuilog" dev="dm-45" ino=448 scontext=u:r:untrusted_app:s0:c59,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.ekissmartwatch
W/OOMEventManagerFK: Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/DefaultDispatch: type=1400 audit(0.0:59216): avc: denied { search } for name="miuilog" dev="dm-45" ino=448 scontext=u:r:untrusted_app:s0:c59,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.ekissmartwatch
W/DefaultDispatch: type=1400 audit(0.0:59217): avc: denied { search } for name="miuilog" dev="dm-45" ino=448 scontext=u:r:untrusted_app:s0:c59,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.ekissmartwatch
W/DefaultDispatch: type=1400 audit(0.0:59218): avc: denied { search } for name="miuilog" dev="dm-45" ino=448 scontext=u:r:untrusted_app:s0:c59,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.ekissmartwatch
I/Process: Process is going to kill itself!
    java.lang.Exception
        at android.os.Process.killProcess(Process.java:1344)
        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at kotlinx.coroutines.internal.CoroutineExceptionHandlerImplKt.propagateExceptionFinalResort(CoroutineExceptionHandlerImpl.kt:35)
        at kotlinx.coroutines.internal.CoroutineExceptionHandlerImpl_commonKt.handleUncaughtCoroutineException(CoroutineExceptionHandlerImpl.common.kt:52)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:32)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:194)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:230)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:909)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:866)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Dj-EKI** [comment]
```
catch (e:Exception){
    Log.d("BLE_Connection:", e.toString())
}
```

**Comment by LeandroSQ** [comment]
Hello, thank you for your issue. Appreciate the interest on the library :)

I've seen you already figure it out, another suggestion to just capture the timeout issue and not others is to
```kotlin
catch(e: ScanTimeoutException) {
}
```
