### ISSUE TITLE
Stackoverflow exception while scanning

### ISSUE THREAD

**Issue by HowardRHard** [LeandroSQ/android-ble-made-easy#46]
Hey I am using this from the docs:

```
GlobalScope.launch {
    try {
        // Continue with your code handling all the devices found
        val devices = ble.scan(duration = 10000)
    } catch (e: Exception) {
        // Show an Alert or UI with your preferred error message
    } catch (e: ScanFailureException) {
        // Show an Alert or UI with your preferred error message
    }
}
```

I have put it in my ViewModel (using viewModelScope), but have tested with both scopes. When I remove the line "val devices = ble.scan(duration = 10000)" I don't get the exception, does anyone know why I'm getting this?

FATAL EXCEPTION: main
PID: 27338
java.lang.StackOverflowError: stack size 8188KB

**Comment by LeandroSQ** [comment]
Hello there
Thank you for your issue and interest in the library.
That is strange to me, do you happen to have the hole stack trace? So I can take a look at it in more details :)

**Comment by HowardRHard** [comment]
Yeah sure!

```
E  FATAL EXCEPTION: main
                                                                                                    Process, PID: 27338
                                                                                                    java.lang.StackOverflowError: stack size 8188KB
                                                                                                    	at kotlin.coroutines.jvm.internal.ContinuationImpl.getContext(ContinuationImpl.kt:105)
                                                                                                    	at kotlin.coroutines.jvm.internal.ContinuationImpl.<init>(ContinuationImpl.kt:102)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$scan$1.<init>(Unknown Source:2)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(Unknown Source:29)
```

... The bit below is repeated a bunch of times, so have removed it for readability ...

```
2024-02-01 15:21:28.881 27338-27338 AndroidRuntime          						                E  	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan(BLE.kt:556)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.scan$default(BLE.kt:554)
                                                                                                    	at .Presentation.ViewModel.VerificationViewModel$searchBluetoothDevices$1.invokeSuspend(VerificationViewModel.kt:137)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$verifyLocationState$2$1.invoke(BLE.kt:363)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$verifyLocationState$2$1.invoke(BLE.kt:362)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$verifyLocationStateAsync$1$1.invoke(BLE.kt:331)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$verifyLocationStateAsync$1$1.invoke(BLE.kt:330)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.verifyLocationStateAsync$lambda$6$lambda$4(BLE.kt:330)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE.$r8$lambda$zljK8eZnpYVPUFmJPZIwbXGPK88(Unknown Source:0)
                                                                                                    	at quevedo.soares.leandro.blemadeeasy.BLE$$ExternalSyntheticLambda0.onSuccess(Unknown Source:2)
                                                                                                    	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@403e993, Dispatchers.Main.immediate]
```

**Comment by LeandroSQ** [comment]
Awesome, this helps a lot.
I will investigate the reason behind this

**Comment by LeandroSQ** [comment]
Think I found something:
https://github.com/LeandroSQ/android-ble-made-easy/commit/6f78b25eb8ea54b036310dffb115feb6750be4c9
On this commit there was an recursive call to itself, not sure how it didn't affect anyone but... yeah

**Comment by HowardRHard** [comment]
Great! Hopefully that is the issue, do you know when we can get the fix if so?

**Comment by LeandroSQ** [comment]
Since it is a simple fix, I will try to get a hotfix later today, but I'm going on vacation tomorrow so I can't promise.
Or if you would be so kind, and want your name on the project as contributor, you just need to remove [this line](https://github.com/LeandroSQ/android-ble-made-easy/blob/ed0faa596d47f3c28676c22cdfd83c190a0a93d2/lib/src/main/java/quevedo/soares/leandro/blemadeeasy/BLE.kt#L556C3-L556C66) from BLE.kt line 554, test it and put out a PR :)

**Comment by LeandroSQ** [comment]
Also, if you want to keep using the library before the fix is out, I suggest giving a try to scanAsync instead. It is a different API, but nothing too different.

**Comment by LeandroSQ** [comment]
Please try v1.9.2 which includes a fix for the issue.
Thank you :)
